[versions]
indra = "3.2.0"

[plugins]
gradleGitProperties = { id = "com.gorylenko.gradle-git-properties", version = "2.5.4" }
indra = { id = "net.kyori.indra", version.ref = "indra" }
indra-checkstyle = { id = "net.kyori.indra.checkstyle", version.ref = "indra" }
indra-git = { id = "net.kyori.indra.git", version.ref = "indra" }
jib = { id = "com.google.cloud.tools.jib", version = "3.5.2" }
sentry = { id = "io.sentry.jvm.gradle", version = "5.12.2" }
spotless = { id = "com.diffplug.spotless", version = "8.1.0" }
spring-boot = { id = "org.springframework.boot", version = "3.5.9" }
spring-deps = { id = "io.spring.dependency-management", version = "1.1.7" }
